name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Check format
        run: crystal tool format --check

  test:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
